-- ==========================================
-- SmartERP - Complete PostgreSQL Database Setup
-- Run this script in the Supabase SQL Editor
-- ==========================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Clean existing tables (in order of dependencies)
drop table if exists public.audit_logs cascade;
drop table if exists public.gst_records cascade;
drop table if exists public.inventory_transactions cascade;
drop table if exists public.transactions cascade;
drop table if exists public.vouchers cascade;
drop table if exists public.invoices cascade;
drop table if exists public.suppliers cascade;
drop table if exists public.customers cascade;
drop table if exists public.stock_items cascade;
drop table if exists public.units_of_measure cascade;
drop table if exists public.stock_groups cascade;
drop table if exists public.ledgers cascade;
drop table if exists public.ledger_groups cascade;
drop table if exists public.companies cascade;
drop table if exists public.profiles cascade;

-- ==========================================
-- 1. Users Module (Profiles mapped to Auth)
-- ==========================================
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  name text,
  role text default 'editor', -- 'admin', 'editor', 'viewer'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

-- Trigger to automatically insert profile on auth user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)));
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 2. Companies Module
-- ==========================================
create table public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  fy text not null default 'FY 26-27', -- Financial Year
  gstin text,
  state text default 'Maharashtra (MH)',
  address text,
  contact_info text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.companies enable row level security;
create policy "Allow full access to companies" on public.companies for all using (true);

-- ==========================================
-- 3. Groups Module (Ledger Groups)
-- ==========================================
create table public.ledger_groups (
  id bigint generated by default as identity primary key,
  name text not null unique, -- 'Assets', 'Liabilities', 'Income', 'Expenses'
  nature text not null -- 'Debit' or 'Credit'
);

insert into public.ledger_groups (name, nature) values
  ('Assets', 'Debit'),
  ('Liabilities', 'Credit'),
  ('Income', 'Credit'),
  ('Expenses', 'Debit');

-- ==========================================
-- 4. Ledgers Module (Chart of Accounts)
-- ==========================================
create table public.ledgers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  group_id bigint references public.ledger_groups(id) on delete restrict,
  name text not null,
  type text not null, -- 'Customer', 'Supplier', 'Expense', 'Income', 'Bank', 'Cash', 'Stock'
  opening_balance numeric(15, 2) default 0.00,
  balance_type text default 'Dr', -- 'Dr' or 'Cr'
  gstin text,
  contact_info text,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.ledgers enable row level security;
create policy "Allow full access to ledgers" on public.ledgers for all using (true);

-- ==========================================
-- 5. Stock Groups Module
-- ==========================================
create table public.stock_groups (
  id bigint generated by default as identity primary key,
  name text not null unique -- 'Electronics', 'Furniture', 'Groceries', 'Medical'
);

insert into public.stock_groups (name) values
  ('Electronics'),
  ('Furniture'),
  ('Groceries'),
  ('Medical');

-- ==========================================
-- 6. Units Module (Units of Measure)
-- ==========================================
create table public.units_of_measure (
  id bigint generated by default as identity primary key,
  code text not null unique, -- 'PCS', 'KG', 'BOX', 'LTR'
  description text
);

insert into public.units_of_measure (code, description) values
  ('PCS', 'Pieces'),
  ('KG', 'Kilograms'),
  ('BOX', 'Boxes'),
  ('LTR', 'Litres');

-- ==========================================
-- 7. Stock Items Module
-- ==========================================
create table public.stock_items (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  group_id bigint references public.stock_groups(id) on delete restrict,
  unit_id bigint references public.units_of_measure(id) on delete restrict,
  name text not null,
  sku text,
  purchase_price numeric(15, 2) not null default 0.00,
  selling_price numeric(15, 2) not null default 0.00,
  qty_initial integer default 0,
  qty_current integer default 0,
  qty_reserved integer default 0,
  qty_damaged integer default 0,
  gst_percentage numeric(5, 2) default 18.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.stock_items enable row level security;
create policy "Allow full access to stock items" on public.stock_items for all using (true);

-- ==========================================
-- 8. Customers Module
-- ==========================================
create table public.customers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  name text not null,
  mobile text,
  address text,
  outstanding_balance numeric(15, 2) default 0.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.customers enable row level security;
create policy "Allow full access to customers" on public.customers for all using (true);

-- ==========================================
-- 9. Suppliers Module
-- ==========================================
create table public.suppliers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  name text not null,
  mobile text,
  address text,
  outstanding_balance numeric(15, 2) default 0.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.suppliers enable row level security;
create policy "Allow full access to suppliers" on public.suppliers for all using (true);

-- ==========================================
-- 10. Invoices Module (Billing System)
-- ==========================================
create table public.invoices (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  invoice_no text not null unique,
  date date not null,
  invoice_type text not null, -- 'GST Invoice', 'Proforma Invoice', 'Quotation', 'Estimate'
  customer_name text not null,
  subtotal numeric(15, 2) not null,
  gst_amount numeric(15, 2) not null,
  grand_total numeric(15, 2) not null,
  details jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.invoices enable row level security;
create policy "Allow full access to invoices" on public.invoices for all using (true);

-- ==========================================
-- 11. Voucher Entries Module
-- ==========================================
create table public.vouchers (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  voucher_no text not null unique,
  date date not null,
  type text not null, -- 'Contra', 'Payment', 'Receipt', 'Journal', 'Purchase', 'Sales', 'Credit Note', 'Debit Note'
  party_name text not null,
  amount numeric(15, 2) not null,
  status text not null default 'Cleared', -- 'Cleared', 'Pending', 'Cancelled'
  details jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.vouchers enable row level security;
create policy "Allow full access to vouchers" on public.vouchers for all using (true);

-- ==========================================
-- 12. Bookkeeping Transactions Module (Double Entry Ledger Postings)
-- ==========================================
create table public.transactions (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  voucher_id bigint references public.vouchers(id) on delete cascade,
  ledger_id bigint references public.ledgers(id) on delete restrict not null,
  debit numeric(15, 2) default 0.00,
  credit numeric(15, 2) default 0.00,
  narration text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.transactions enable row level security;
create policy "Allow full access to transactions" on public.transactions for all using (true);

-- ==========================================
-- 13. Inventory Transactions Module (Stock In / Out / Transfer)
-- ==========================================
create table public.inventory_transactions (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  voucher_id bigint references public.vouchers(id) on delete cascade,
  item_id bigint references public.stock_items(id) on delete restrict not null,
  qty_in integer default 0,
  qty_out integer default 0,
  transaction_type text not null, -- 'Stock In', 'Stock Out', 'Stock Transfer', 'Inventory Adjustment'
  narration text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.inventory_transactions enable row level security;
create policy "Allow full access to inventory transactions" on public.inventory_transactions for all using (true);

-- ==========================================
-- 14. GST Records Module
-- ==========================================
create table public.gst_records (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  voucher_id bigint references public.vouchers(id) on delete cascade,
  invoice_no text,
  taxable_value numeric(15, 2) not null,
  cgst numeric(15, 2) default 0.00,
  sgst numeric(15, 2) default 0.00,
  igst numeric(15, 2) default 0.00,
  total_gst numeric(15, 2) not null,
  gst_type text not null, -- 'CGST+SGST' or 'IGST'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.gst_records enable row level security;
create policy "Allow full access to gst records" on public.gst_records for all using (true);

-- ==========================================
-- 15. Audit Logs Module (Logs for ERP security and audit trails)
-- ==========================================
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete set null,
  action text not null, -- 'INSERT', 'UPDATE', 'DELETE'
  table_name text not null,
  record_id bigint not null,
  old_data jsonb,
  new_data jsonb,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.audit_logs enable row level security;
create policy "Allow read access to audit logs" on public.audit_logs for select using (true);

-- ==========================================
-- Seed Data
-- ==========================================
-- Seed 1 Company
insert into public.companies (id, name, fy, gstin, state, address, contact_info)
values (1, 'Vardhaman Distributors Pvt. Ltd.', 'FY 26-27', '27AADCT1234E1Z5', 'Maharashtra (MH)', 'Mumbai Main Office', '+91 98765 43210');

-- Seed Ledgers
insert into public.ledgers (id, company_id, group_id, name, type, opening_balance, balance_type, gstin, contact_info, address)
values
  (1, 1, 1, 'HDFC Bank Current Account', 'Bank', 500000.00, 'Dr', '27HDFCB9928A1Z0', '+91 22 6654 3210', 'HDFC Branch, Mumbai'),
  (2, 1, 1, 'Cash-in-Hand', 'Cash', 120000.00, 'Dr', null, null, null),
  (3, 1, 4, 'Office Rent Expenses', 'Expense', 0.00, 'Dr', null, null, null);
